development:
  secret_key_base: b2f0e5ff90f9d3ad6716ba98bef89c394db3bbcbb7febba29a9489587b89b341cc24a942d2fbde4580faf12075ad6671e84d8d76ab855b4a479f7dad23d9fd41
  email_provider_username: <%= ENV["SENDGRID_USERNAME"] %>
  email_provider_password: <%= ENV["SENDGRID_PASSWORD"] %>
  domain_name: google.com
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  owner_email: <%= ENV["OWNER_EMAIL"] %>

test:
  secret_key_base: b2f0e5ff90f9d3ad6716ba98bef89c394db3bbcbb7febba29a9489587b89b341cc24a942d2fbde4580faf12075ad6671e84d8d76ab855b4a479f7dad23d9fd41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  email_provider_username: <%= ENV["SENDGRID_USERNAME"] %>
  email_provider_password: <%= ENV["SENDGRID_PASSWORD"] %>
  domain_name: example.com
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  owner_email: ekr990011@yahoo.com
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
